export const sampleComponents = [
  {
    id: 1,
    name: "Resistor (100Ω, 1/4W)",
    manufacturer: "Vishay",
    partNumber: "CFR-25JB-52-100R",
    description: "Carbon Film Resistor, ±5% Tolerance, High Precision",
    quantity: 2450,
    location: "R-Shelf-A1",
    unitPrice: 0.75,
    criticalLowThreshold: 500,
    category: "Resistors",
    datasheetLink: "https://example.com/datasheet1.pdf",
    lastUpdated: "2024-07-28",
    addedDate: "2024-03-01",
    supplier: "DigiKey",
    status: "active"
  },
  {
    id: 2,
    name: "NE555 Precision Timer IC",
    manufacturer: "Texas Instruments",
    partNumber: "NE555DR",
    description: "Single Precision Timer, SOIC-8 Package",
    quantity: 15,
    location: "IC-Box-F1",
    unitPrice: 12.50,
    criticalLowThreshold: 25,
    category: "Integrated Circuits (ICs)",
    datasheetLink: "https://example.com/datasheet2.pdf",
    lastUpdated: "2024-08-01",
    addedDate: "2024-04-15",
    supplier: "Mouser",
    status: "low_stock"
  },
  {
    id: 3,
    name: "ESP32-WROOM-32U Wi-Fi Module",
    manufacturer: "Espressif Systems",
    partNumber: "ESP32-WROOM-32UE",
    description: "Dual-core Wi-Fi & Bluetooth SoC Module, PCB Antenna",
    quantity: 8,
    location: "IC-Box-F4",
    unitPrice: 285.00,
    criticalLowThreshold: 10,
    category: "Integrated Circuits (ICs)",
    datasheetLink: "https://example.com/datasheet3.pdf",
    lastUpdated: "2024-07-25",
    addedDate: "2024-01-10",
    supplier: "Official Distributor",
    status: "active"
  },
  {
    id: 4,
    name: "Arduino Uno R3 Development Board",
    manufacturer: "Arduino",
    partNumber: "A000066",
    description: "Microcontroller Board based on ATmega328P",
    quantity: 0,
    location: "DevBoard-Rack-I1",
    unitPrice: 950.00,
    criticalLowThreshold: 2,
    category: "Microcontrollers/Dev Boards",
    datasheetLink: "https://example.com/datasheet4.pdf",
    lastUpdated: "2024-07-30",
    addedDate: "2024-02-05",
    supplier: "Arduino Store",
    status: "out_of_stock"
  },
  {
    id: 5,
    name: "STM32F401RET6 Microcontroller",
    manufacturer: "STMicroelectronics",
    partNumber: "STM32F401RET6",
    description: "ARM Cortex-M4 32-bit MCU, 512KB Flash, LQFP64",
    quantity: 125,
    location: "IC-Box-F2",
    unitPrice: 485.00,
    criticalLowThreshold: 20,
    category: "Integrated Circuits (ICs)",
    datasheetLink: "https://example.com/datasheet5.pdf",
    lastUpdated: "2024-08-02",
    addedDate: "2024-05-10",
    supplier: "STMicroelectronics",
    status: "active"
  }
];
